# Generated by Django 5.0.1 on 2024-02-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUTemperatureTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.CharField(default=None, max_length=100000)),
                ('cpu_temperature', models.FloatField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(default=None, max_length=1000)),
                ('ram_usage', models.FloatField()),
                ('cpu_fan_speed', models.FloatField()),
            ],
            options={
                'db_table': 'cpu_temperature_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
