# Generated by Django 5.0.1 on 2024-02-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cputemperaturetransaction',
            name='cpu_fan_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cputemperaturetransaction',
            name='ram_usage',
            field=models.FloatField(null=True),
        ),
    ]
