# Generated by Django 5.0.1 on 2024-03-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cputemperaturetransaction_block_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(default=None, max_length=10000, null=True)),
                ('difficulty_level', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'load_algorithm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='cputemperaturetransaction',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
